name: CI-Main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  common:
    uses: Aahil684/github-actions-reusable/.github/workflows/ci-main.yml@main
    with:
      component_name: user
      app_type: nodejs